# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: data_catalog
    ports:
      - 5432:5432
  # To connect to the postgres database from the command line client, use:
  #   docker run -it --rm --network data-catalog_default postgres psql -h db -U postgres data_catalog

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
